export {default as SplashScreen} from "./SplashScreen/SplashScreen"
export {default as Login} from "./Login/Login"
export {default as Register} from "./Register/Register"
export {default as Home} from "./Home/Home"
export {default as OtpVerfication} from "./OtpVerification/OtpVerification"
export {default as FoodItemPage} from "./FoodItemPage/FoodItemPage"
export {default as AddCartPage} from "./AddCartPage/AddCartPage"