export default{
    ADD_TO_CART:'ADD__TO_CART',
    DELETE_ITEM:'DELETE_ITEM',
    INCREASE_QUANTITY:'INCREASE_QUANTITY',
    DECREASE_QUANTITY:'DECREASE_QUANTITY',
    TOTAL_PRICE:'TOTAL_PRICE',
    LOGIN:"LOGIN"
    
}